name: Build Free APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Package Name to Free (gamesnotes)
        run: sed -i 's/applicationId = ".*/applicationId = "com.spinel.gamesnotes"/g' app/build.gradle.kts

      - name: Build Free APK (With Ads)
        run: ./gradlew assembleRelease -PisPersonal=false

      - name: Rename Free APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/GameNotes-Free.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameNotes_Free_APK
          path: app/build/outputs/apk/release/GameNotes-Free.apk
